#!/usr/bin/env tsx

import fs from 'fs'
import path from 'path'

interface ComponentData {
  title: string
  description: string
  componentPath: string
  previewPath: string
  category: string
  tags: string[]
  installation: {
    cliSteps: Array<{
      step: number
      title: string
      code: string
    }>
    manualSteps: Array<{
      step: number
      title: string
      code: string
    }>
  }
  usage: {
    steps: Array<{
      step: number
      title: string
      code: string
    }>
  }
  features: string[]
  dependencies: string[]
}

interface ComponentMapping {
  [key: string]: ComponentData & {
    previewComponent: string // Will be the import statement
  }
}

/**
 * Generate component mapping file for a specific component type
 */
function generateComponentMappingFile(
  componentType: string,
  dataPath: string,
  outputPath: string
) {
  try {
    // Read the JSON data
    const dataContent = fs.readFileSync(dataPath, 'utf-8')
    const data: Record<string, ComponentData> = JSON.parse(dataContent)
    
    // Generate the mapping object
    const mapping: ComponentMapping = {}
    Object.keys(data).forEach((key, index) => {
      const componentKey = (index + 1).toString()
      mapping[componentKey] = {
        ...data[key],
        previewComponent: `import { ${key.charAt(0).toUpperCase() + key.slice(1)}Preview } from '@/app/docs/(content)/preview/${key}'`
      }
    })
    
    // Generate the TypeScript file content
    const fileContent = `// Auto-generated component mapping for ${componentType}
// This file is automatically generated - do not edit manually
// Run: npm run generate:mapping ${componentType}

import React from 'react'
import { generateComponentMetadata } from '@/lib/metadata'
import { Metadata } from 'next'
import ComponentTemplate from '@/components/ComponentTemplate'
import ${Object.keys(data).map(key => `import { ${key.charAt(0).toUpperCase() + key.slice(1)}Preview } from '@/app/docs/(content)/preview/${key}'`).join('\nimport ')}
import ${componentType}Data from '@/app/docs/(content)/data/${componentType}.json'
import { generateComponentMapping } from '@/lib/component-mapper'

// Dynamic metadata generation
export async function generateMetadata({ params }: { params: { slug: string[] } }): Promise<Metadata> {
  const componentName = params.slug[0] || '${componentType}'
  return generateComponentMetadata(componentName)
}

// Automated component mapping - no more manual updates needed!
const ${componentType}Components = generateComponentMapping(
  ${componentType}Data,
  {
${Object.keys(data).map(key => `    ${key}: ${key.charAt(0).toUpperCase() + key.slice(1)}Preview`).join(',\n')}
  }
)

// Dynamic page component
export default function ${componentType.charAt(0).toUpperCase() + componentType.slice(1)}Page({ params }: { params: { slug: string[] } }) {
  const componentKey = params.slug[0] || '1'
  const component = ${componentType}Components[componentKey as keyof typeof ${componentType}Components]

  if (!component) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <h1 className="text-2xl font-bold mb-4">Component Not Found</h1>
          <p className="text-gray-600">The ${componentType} component "{componentKey}" could not be found.</p>
          <p className="text-sm text-gray-500 mt-2">Available components: {Object.keys(data).map((_, i) => i + 1).join(', ')}</p>
        </div>
      </div>
    )
  }

  return (
    <ComponentTemplate 
      title={component.title}
      description={component.description}
      componentPath={component.componentPath}
      previewComponent={component.previewComponent}
      installation={component.installation}
      usage={component.usage}
    />
  )
}
`
    
    // Write the file
    fs.writeFileSync(outputPath, fileContent, 'utf-8')
    console.log(`✅ Generated ${componentType} component mapping file: ${outputPath}`)
    
  } catch (error) {
    console.error(`❌ Error generating ${componentType} mapping:`, error)
  }
}

/**
 * Main function to generate mappings for all component types
 */
function main() {
  const componentTypes = ['carousel', 'card', 'showcase', 'sidemenu', 'team', 'liquid-frame']
  
  componentTypes.forEach(componentType => {
    const dataPath = path.join(process.cwd(), 'src/app/docs/(content)/data', `${componentType}.json`)
    const outputPath = path.join(process.cwd(), 'src/app/docs/(content)/components2', componentType, '[...slug]', 'page.tsx')
    
    // Check if data file exists
    if (fs.existsSync(dataPath)) {
      generateComponentMappingFile(componentType, dataPath, outputPath)
    } else {
      console.log(`⚠️  Skipping ${componentType} - no data file found at ${dataPath}`)
    }
  })
}

// Run if called directly
if (require.main === module) {
  main()
}

export { generateComponentMappingFile }
